title: Matt Kolarik # your name (or website title) here
logo: "/images/maryland_flag.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Trial run github site for 486 
  <br><br>
  Projects From UMBC below 
  <br><br>
  <a href="https://www.linkedin.com/in/matthew-kolarik-9429b3136//">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
